apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d-web
  namespace: production
spec:
  replicas: 5
  template:
    metadata:
      labels:
        web: rails
    spec:
      volumes:
      - name: photos
        azureFile:
          secretName: topsecret
          shareName: photos
          readOnly: false
      containers:
      - name: web
        image: chyld/web:5
        env:
        - name: PGPASSWORD
          value: efe6358aa3
        - name: REDIS_URL
          value: redis://redis:6379/0
        ports:
        - containerPort: 3333
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: photos
        command: ["./scripts/start-dev.sh"]
        args: ["rails", "server"]

      - name: worker
        image: chyld/web:5
        env:
        - name: PGPASSWORD
          value: efe6358aa3
        - name: REDIS_URL
          value: redis://redis:6379/0
        - name: AZURE_URL
          value: https://chyld.blob.core.windows.net/photos
        - name: AZURE_ACCOUNT
          value: chyld
        - name: AZURE_CONTAINER
          value: photos
        - name: AZURE_KEY
          value: uLfpKbW4UpElKZoqFmoeXw7LwXQZ6iTbtKHGiMZ8h5bwLVDLmFVX3VMsPw1rb+SxmgdaPYbMApXYe0c+Sz0O0A==
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: photos
        command: ["./scripts/start-sidekiq.sh"]
        args: ["sidekiq", "-c", "3"]

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d-logger
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      labels:
        api: logger
    spec:
      containers:
      - name: logger
        image: chyld/logger:5
        env:
        - name: PGPASSWORD
          value: efe6358aa3
        ports:
        - containerPort: 5555
        command: ["./scripts/start-dev.sh"]
        args: ["rails", "server"]

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d-postgres
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        sql: postgres
    spec:
      containers:
      - name: postres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: efe6358aa3

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d-redis
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        cache: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: production
  labels:
    service: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3333
  selector:
    web: rails

---

apiVersion: v1
kind: Service
metadata:
  name: logger
  namespace: production
  labels:
    service: logger
spec:
  ports:
  - port: 5555
  selector:
    api: logger

---

apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: production
  labels:
    service: postgres
spec:
  ports:
  - port: 5432
  selector:
    sql: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: production
  labels:
    service: redis
spec:
  ports:
  - port: 6379
  selector:
    cache: redis
