version: '3'
services:
  web:
    env_file: .env
    build:
      context: ./learn
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
      - redis
      - logger
    ports:
     - "3333:3333"
    command: ["./scripts/start-dev.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  logger:
    env_file: .env
    build:
      context: ./logger
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
    command: ["./scripts/start-dev.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  worker:
    env_file: .env
    image: advrails_web
    depends_on:
      - pg
      - redis
      - logger
    command: ["./scripts/start-sidekiq.sh", "sidekiq", "-c", "3"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=efe6358aa3

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  redis:
    image: redis

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

# NOTES
# command: ["sleep", "infinity"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
