version: '3'
services:
  web:
    build:
      context: ./learn
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
      - redis
      - logger
    ports:
     - "3333:3333"
    environment:
      - PGPASSWORD=pass1234
      - REDIS_URL=redis://redis:6379/0
    command: ["./scripts/start-dev.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  logger:
    build:
      context: ./logger
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
    environment:
      - PGPASSWORD=pass1234
    command: ["./scripts/start-dev.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  worker:
    image: advrails_web
    depends_on:
      - pg
      - redis
      - logger
    environment:
      - PGPASSWORD=pass1234
      - REDIS_URL=redis://redis:6379/0
    command: ["./scripts/start-sidekiq.sh", "sidekiq", "-c", "3"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  pg:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=pass1234

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  redis:
    image: "redis"

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

# NOTES
# command: ["sleep", "infinity"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
