version: '3'
services:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  web:
    env_file: .env
    build:
      context: ./learn
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
      - redis
      - logger
      - worker
    ports:
     - "3333:3333"
    volumes:
      - "photos:/usr/src/app/uploads"
    command: ["./scripts/start-db.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  worker:
    env_file:
      - .env
      - .env-azure
    build:
      context: ./learn
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
      - redis
      - logger
    volumes:
      - "photos:/usr/src/app/uploads"
    command: ["./scripts/start-sidekiq.sh", "sidekiq", "-c", "3"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  logger:
    env_file: .env
    build:
      context: ./logger
      dockerfile: Dockerfile-dev
    depends_on:
      - pg
    command: ["./scripts/start-dev.sh", "rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=efe6358aa3

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  redis:
    image: redis

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

volumes:
  photos:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

# NOTES
# command: ["sleep", "infinity"]
# dc up web
# dc up test

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
