apiVersion: v1
kind: Namespace
metadata:
  name: production

---

apiVersion: v1
kind: Secret
metadata:
  name: topsecret
  namespace: production
type: Opaque
data:
  azurestorageaccountname: Y2h5bGQ=
  azurestorageaccountkey: dUxmcEtiVzRVcEVsS1pvcUZtb2VYdzdMd1hRWjZpVGJ0S0hHaU1aOGg1YndMVkRMbUZWWDNWTXNQdzFyYitTeG1nZGFQWWJNQXBYWWUwYytTejBPMEE9PQ==
