# PRODUCTION DOCKERFILE

FROM ruby:2.4.1

RUN apt-get update && apt-get install vim postgresql-client redis-tools cifs-utils -y

RUN gem install rails

ENV PORT "5555"
ENV HOST "0.0.0.0"
ENV RAILS_ENV "production"

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN bundle install --without development test

EXPOSE 5555
CMD ["rails", "server"]
